---
version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"
